Repository evercam/evercam-server, pull requests merged in 2018-05, with the labels that each got.

#930 Fixed intercom user update issue
  lib/evercam_media/intercom.ex
  lib/evercam_media_web/controllers/camera_share_controller.ex
Labels: in progress

#925 Add telegram bot
  config/config.exs
  image.png
  lib/evercam_media.ex
  lib/evercam_media/evercam_bot/commander.ex
  lib/evercam_media/evercam_bot/commands.ex
  lib/evercam_media/evercam_bot/matcher.ex
  lib/evercam_media/evercam_bot/poller.ex
  lib/evercam_media/evercam_bot/router.ex
  lib/evercam_media/evercam_bot/telegram_supervisor.ex
  lib/evercam_media_web/controllers/snapshot_controller.ex
  lib/evercam_media_web/controllers/user_controller.ex
  lib/evercam_media_web/models/user.ex
  lib/evercam_media_web/router.ex
  mix.exs
  mix.lock
  priv/static/swagger.json
  video.mp4
Labels: in production, in progress

#934 Added delete '/cameras/:id/recordings/snapshots' endpoint.
  lib/evercam_media/snapshot/storage.ex
  lib/evercam_media_web/controllers/snapshot_controller.ex
  lib/evercam_media_web/router.ex
  priv/static/swagger.json
Labels: in production

#935 Add deletion in worker
  config/prod.exs
  lib/evercam_media/snapshot/deletion.ex
  lib/evercam_media/snapshot/storage.ex
  lib/evercam_media/snapshot/worker.ex
  lib/evercam_media_web/models/cloud_recording.ex
Labels: in production
